# Generated by Django 3.2.25 on 2024-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('counselling_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('teacher_type', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('subject_nme', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('scl_category', models.CharField(max_length=50)),
                ('scl_management', models.CharField(max_length=50)),
                ('scl_panel', models.CharField(max_length=50)),
                ('directorate', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('level1_approver', models.CharField(max_length=50)),
                ('level2_approver', models.CharField(max_length=50)),
                ('application_status', models.CharField(max_length=50)),
                ('vac_category', models.CharField(max_length=50)),
                ('vac_management', models.CharField(max_length=50)),
                ('vac_panel', models.CharField(max_length=50)),
                ('seniority_order', models.IntegerField()),
                ('rule', models.CharField(max_length=50)),
                ('vac_updated_by', models.CharField(max_length=50)),
                ('counselling_school_type', models.CharField(max_length=50)),
                ('counselling_minority', models.CharField(max_length=50)),
                ('vacancy_minority', models.CharField(max_length=50)),
                ('candidate_updated_by', models.CharField(max_length=50)),
                ('vacancy_publish_status', models.CharField(max_length=50)),
                ('seniority_reset_sts', models.CharField(max_length=50)),
                ('seniority_publish_status', models.CharField(max_length=50)),
                ('seniority_chlg_status', models.CharField(max_length=50)),
                ('vaccancy_chlg_status', models.CharField(max_length=50)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'staff_counselling_mainpage',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schoolnew_district',
            },
        ),
    ]
